# Generated by Django 4.2.1 on 2023-05-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'audience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatabaseManager',
            fields=[
                ('password', models.CharField(max_length=20)),
                ('manager_username', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'database_manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DirectedMovie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=20)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directed_movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nation', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'director',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_name', models.CharField(max_length=20, unique=True)),
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieSession',
            fields=[
                ('date', models.DateField()),
                ('time_slot', models.IntegerField()),
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'movie_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_name', models.CharField(max_length=20, unique=True)),
                ('platform_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'platform',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('district', models.CharField(blank=True, max_length=25, null=True)),
                ('theatre_name', models.CharField(max_length=25)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('theatre_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'theatre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.director')),
            ],
            options={
                'db_table': 'agreement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.audience')),
            ],
            options={
                'db_table': 'buy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.directedmovie')),
            ],
            options={
                'db_table': 'classify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Located',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.moviesession')),
            ],
            options={
                'db_table': 'located',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NextTo',
            fields=[
                ('pre', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.directedmovie')),
            ],
            options={
                'db_table': 'next_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.moviesession')),
            ],
            options={
                'db_table': 'play',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.audience')),
                ('rating', models.FloatField()),
            ],
            options={
                'db_table': 'rate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MovieDBApp.audience')),
            ],
            options={
                'db_table': 'subscribe',
                'managed': False,
            },
        ),
    ]
